properties([pipelineTriggers([pollSCM('* * * * *')])])
node {
    stage("clone"){
        git branch:'master', url: 'https://github.com/naondaniel/jenkins.git'
    }
    stage("execute"){
        sh "python3 main.py"
    }
}