properties([pipelineTriggers([pollSCM('* * * * *')])])
node {
    stage("clone"){
        git branch:'master', url: 'https://github.com/naondaniel/DevOps0609.git'
    }
    stage("execute"){
        sh "python3 DevOps0609/main.py"
    }
}